### ISSUE TITLE
Map-Reduce Benchmark not working

### ISSUE THREAD

**Issue by NeHalem90** [vhive-serverless/vSwarm#505]
**Describe the bug**

map-reduce benchmark not returning any result

**To Reproduce**
Use single CloudLab's XL170 node

Setup vhive using stock-only arguments
```
git clone --depth=1 https://github.com/vhive-serverless/vhive.git
cd vhive
mkdir -p /tmp/vhive-logs
./scripts/cloudlab/setup_node.sh stock-only
sudo screen -d -m containerd
source /etc/profile && go build
./scripts/cluster/create_one_node_cluster.sh stock-only
```

Clone vSwarm repo, export AWS S3 credentials and environments, and make k8s secrets.
Change knative_yaml's  container image tag to capnp (ex. docker.io/vhiveease/mapreduce-mapper:capnp) because kn function does not deploy as python package dependency cannot be solved,
or can build your own docker file by including capnp to requirement.txt.
Move to map-reduce benchmark directory and execute 
```
../../tools/kn_deploy.sh ./knative_yamls/s3/*
```
Update Mapper address and Reducer address to appropriate one and re-deploy functions by repeating the above instriction.

Go yo vSwarm/tools/invoker
install additional Go Plugins - protobuf by referring to the website below
https://grpc.io/docs/languages/go/quickstart/

build invoker and invoke deployed functions
```
make invoker
echo '[ { "hostname": "driver.default.192.168.1.240.sslip.io" } ]' > endpoints.json
./invoker -port 80 -dbg -time 60 -rps 0.016667
```

**Expected behavior**

**Logs**
Invoker log
```
nehalem@node-0:~/vSwarm/tools/invoker$ ./invoker -port 80 -dbg -time 60 -rps 0.016667
DEBU[2023-03-20T01:31:15.724111025-06:00] Debug logging is enabled
INFO[2023-03-20T01:31:15.724211535-06:00] Reading the endpoints from the file: endpoints.json
DEBU[2023-03-20T01:31:15.724380511-06:00] Invoking: http://driver.default.example.com:80
INFO[2023-03-20T01:32:15.742420012-06:00] Issued / completed requests: 2, 0
INFO[2023-03-20T01:32:15.742474469-06:00] Real / target RPS: 0.00 / 0.016667
INFO[2023-03-20T01:32:15.742494926-06:00] Experiment finished!
INFO[2023-03-20T01:32:15.742511311-06:00] The measured latencies are saved in rps0.00_lat.csv
DEBU[2023-03-20T01:32:15.742495204-06:00] Invoking: http://driver.default.example.com:80
```

Driver Function Queue-Proxy Log
```
{"severity":"INFO","timestamp":"2023-03-20T07:37:01.296950421Z","caller":"logging/config.go:116","message":"Succes ││ sfully created the logger."}
│ {"severity":"INFO","timestamp":"2023-03-20T07:37:01.297056908Z","caller":"logging/config.go:117","message":"Loggin ││ g level set to: info"}
{"severity":"INFO","timestamp":"2023-03-20T07:37:01.297845501Z","logger":"queueproxy","caller":"queue/main.go:380" │
│ ,"message":"Queue container is starting with BreakerParams = queue.BreakerParams{QueueDepth:10, MaxConcurrency:1,  ││ InitialCapacity:1}","commit":"6ec4509","knative.dev/key":"default/driver-00002","knative.dev/pod":"driver-00002-de ││ ployment-584cf57dd5-9f4h8"}
│ {"level":"info","ts":1679297821.2979364,"logger":"fallback","caller":"metrics/metrics_worker.go:76","msg":"Flushin ││ g the existing exporter before setting up the new exporter."}{"level":"info","ts":1679297821.298163,"logger":"fallback","caller":"metrics/prometheus_exporter.go:51","msg":"Cre │
│ ated Prometheus exporter with config: &{knative.dev/internal/serving revision prometheus 5000000000 <nil>  false 9 ││ 091 0.0.0.0}. Start the server for Prometheus exporter."}{"level":"info","ts":1679297821.2982101,"logger":"fallback","caller":"metrics/metrics_worker.go:91","msg":"Success │
│ fully updated the metrics exporter; old config: <nil>; new config &{knative.dev/internal/serving revision promethe ││ us 5000000000 <nil>  false 9091 0.0.0.0}"}
```

Driver Function User-Container Log
```
INFO:root:Driver received a request
INFO:root:Invoking Mapper 0
INFO:root:Invoking Mapper 1
INFO:root:Invoking Mapper 2
INFO:root:Invoking Mapper 3
INFO:root:Invoking Mapper 4
INFO:root:Invoking Mapper 5
INFO:root:Invoking Mapper 6
INFO:root:Invoking Mapper 7
ERROR:grpc._server:Exception calling application: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNKNOWN
    details = "Exception calling application: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied"
    debug_error_string = "{"created":"@1679302933.630953319","description":"Error received from peer ipv4:192.168.1.240:80","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Exception calling application: An error occ
urred (AccessDenied) when calling the GetObject operation: Access Denied","grpc_status":2}"
>
Traceback (most recent call last):
  File "/root/.local/lib/python3.8/site-packages/grpc/_server.py", line 444, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "./main.py", line 136, in SayHello
    DriveFunction(driverArgs)
  File "/app/driver.py", line 65, in DriveFunction
    reduce_input_keys = args['prepareReduceKeys'](all_result_futures, NUM_REDUCERS)
  File "./main.py", line 122, in prepareReduceKeys
    for result_keys in all_result_futures:
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 619, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./main.py", line 92, in call_mapper
    resp = stub.Map(req)
  File "/root/.local/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/root/.local/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.UNKNOWN
    details = "Exception calling application: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied"
    debug_error_string = "{"created":"@1679302933.630953319","description":"Error received from peer ipv4:192.168.1.240:80","file":"src/core/lib/surface/call.cc","file_line":1066,"grpc_message":"Exception calling application: An error occurred (AccessDenied) when calling the GetObject operation: Access Denied","grpc_status":2}"
```

**Notes**
Currently, we support only Ubuntu 18 (x86) bare-metal hosts, however
we encourage the users to reports Issues that appear in different settings.
We will try to help and potentially include these scenarios into our CI

if given enough interest from the community.

**Comment by ustiugov** [comment]
@shyamjesal could you please take a look as you were the last using it?

**Comment by ustiugov** [comment]
we need to add a config parameter for S3 bucket, as proposed here: https://github.com/vhive-serverless/vSwarm/pull/338/files

**Comment by shyamjesal** [comment]
What all ENV variables did you export?
@NeHalem90

**Comment by ustiugov** [comment]
@NeHalem90 is the issue still relevant?

**Comment by NeHalem90** [comment]
No Thanks!
